version: '3.6'

services:
  nginx:
    image: nginx:latest 
    depends_on:
      - wptinamou
      - php-fpm
    ports:
      - "8123:80"
    volumes:
      #- ./nginx/default:/etc/nginx/sites-available/default
      #- ./nginx/default:/etc/nginx/sites-enabled/default
      - ./nginx/default:/etc/nginx/conf.d/default.conf
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log
      #- ./sites/:/usr/share/nginx/html/
     # - ./sites:/var/www/html
      #- ./sites/:/var/www/html/
    restart: always


  php-fpm:
    image: php:7.2-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./wordpress/install:/var/www/html
    #  - ./sites:/usr/share/nginx/html
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
  
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./db:/var/lib/data
    container_name: db
    restart: unless-stopped

  wptinamou:
    depends_on:
      - db
      - php-fpm
    image: wordpress:latest
    container_name: wptinamou
    environment:
    - WORDPRESS_DB_HOST=db:3306
    - WORDPRESS_DB_USER=${WP_DB_USER}
    - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
    - WORDPRESS_DB_NAME=wordpress
    volumes:
    #  - ./sites:/usr/share/nginx/html
      - ./wordpress/install:/var/www/html
    restart: always  
  

  #  build: ./db
  #drupal:
  #  build: ./drupal






