version: '3.3'

services:
  nginx:
    build: ./nginx 
    ports:
      - "8123:80"
    links:
      - php-fpm
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/default:/etc/nginx/sites-enabled/default

      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log
      - ./sites/:/usr/share/nginx/html/
      #- ./sites/:/var/www/html/

  php-fpm:
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
      - ./sites:/usr/share/nginx/html
  #db:
  #  build: ./db
  #drupal:
  #  build: ./drupal






