version: '3.3'

services:
  nginx:
    build: ./nginx 
    ports:
      - "8123:80"
    links:
      - php-fpm
    volumes:
      - ./nginx/dev.drupal.conf:/etc/nginx/sites-available/dev.drupal.conf
      - ./nginx/dev.drupal.conf:/etc/nginx/sites-enabled/dev.drupal.conf

      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log

  php-fpm:
    build: ./php-fpm
  db:
    build: ./db
  drupal:
    build: ./drupal






